### ISSUE TITLE
Logging In

### ISSUE THREAD

**Issue by mrobaer** [Danter14/Xterium#4]
The game does not accept my password when I want to log back in.  This also happens at the admin page when trying to access it.

**Comment by Danter14** [comment]
Me all the works on this side

**Comment by mrobaer** [comment]
Also, when trying to register another user:

http://127.0.0.1/Xterium-1.0/index.php?page=register

Fatal error: Uncaught exception 'ErrorException' with message 'Undefined offset: 8192' in D:\WWW\Xterium-1.0\includes\GeneralFunctions.php:791 Stack trace: #0 D:\WWW\Xterium-1.0\includes\GeneralFunctions.php(791): errorHandler(8, 'Undefined offse...', 'D:\\WWW\\Xterium-...', 791, Array) #1 [internal function]: exceptionHandler(Object(ErrorException)) #2 {main} thrown in D:\WWW\Xterium-1.0\includes\GeneralFunctions.php on line 791

**Comment by Danter14** [comment]
I will be a test server for you

**Comment by Qwatayean** [comment]
The issue is, when you create an account as Admin, it registers with 2Moons hashed password, not with MD5.  Use this - http://md5encryption.com/ - and change your hashed code in your account on phpMyAdmin. I'll fix Install page later with new password system as MD5, aswell register issue.

About register issue, im working on it.
